import { StyleSheet } from 'react-native';
import { Fonts, Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
	safeArea: { flex: 1, padding: 30, backgroundColor: '#ffffff' },
	authSafeArea: { backgroundColor: '#eeeeee' },
	subscreenSafeArea: { backgroundColor: '#eeeeee' },
	accountSubscreenSafeArea: { padding: Spacing.four },
	accountSubscreenContent: { paddingHorizontal: 14 },
	accountScreen: { flex: 1, position: 'relative' },
	accountScroll: { flex: 1 },
	themeToggleAbove: { position: 'absolute', top: -15, right: 0, zIndex: 2 },
	content: { gap: Spacing.three, paddingTop: 20, paddingBottom: 20 },
	greeting: { textAlign: 'center', color: '#0a0a0a', fontWeight: '300' },
	loggedGreeting: { fontSize: 22 }, email: { fontSize: 16 },
	primaryButton: { marginBottom: 10, padding: 10, borderRadius: 8, alignItems: 'center', backgroundColor: '#e9e6df' },
	primaryText: { color: '#000', fontWeight: '700' },
	primaryDadosText: { textDecorationLine: 'underline', color: '#0a0a0a' },
	logout: { alignSelf: 'flex-start', paddingVertical: Spacing.four, width: '100%', textAlign: 'center', borderTopWidth: 1, borderBottomWidth: 1, borderColor: '#dedbd5' },
	logoutText: { color: '#0a0a0a', fontWeight: '600', width: '100%', textAlign: 'center', borderWidth: 1, borderColor: '#0a0a0a', borderRadius: 5, padding: 8 },
	tileGrid: { display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start', flexWrap: 'wrap', gap: 5},
	tile: { width: '49%', padding: Spacing.three, borderRadius: 16, backgroundColor: '#e9e6df', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
	preferenceBlock: { gap: 4 },
	preference: { paddingVertical: Spacing.three, borderBottomWidth: 0, borderBottomColor: '#dedbd5', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
	notificationSwitch: { width: 30, height: 16, padding: 3, borderRadius: 14, justifyContent: 'center' },
	notificationSwitchOn: { backgroundColor: '#0a0a0a', alignItems: 'flex-end' },
	notificationSwitchOff: { backgroundColor: '#dedbd5', alignItems: 'flex-start' },
	notificationThumb: { width: 12, height: 12, borderRadius: 11, backgroundColor: '#ffffff', shadowColor: '#0a0a0a', shadowOpacity: 0.15, shadowRadius: 2, shadowOffset: { width: 0, height: 1 }, elevation: 2 },
	helpTitle: { fontSize: 18, textAlign: 'center' },
	helpButton: { padding: Spacing.four, borderRadius: 8, borderWidth: 1, borderColor: '#0a0a0a', alignItems: 'center' },
	powered: { textAlign: 'center', fontSize: 10, color: '#777' },
	card: { gap: Spacing.three, padding: Spacing.three, borderRadius: 8, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e6e2dc' },
	cardTitle: { fontSize: 20 },
	divider: { height: 1, backgroundColor: '#dedbd5', marginTop: 10, marginBottom: 10 },
	outlineButton: { padding: Spacing.three, borderRadius: 8, borderWidth: 1, borderColor: '#7b7772', alignItems: 'center' },
	outlineButtonNone: { display: 'none' },
	googleButton: { flexDirection: 'row', justifyContent: 'center', gap: Spacing.two, minHeight: 48 },
	centerText: { fontFamily: Fonts.medium, fontSize: 13, lineHeight: 16, fontWeight: '500', color: '#0a0a0a', textAlign: 'center' },
	input: { minHeight: 42, paddingHorizontal: 12, paddingVertical: 0, borderRadius: 8, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#0a0a0a', fontSize: 15, fontFamily: Fonts.sans },
	passwordInputWrap: { minHeight: 42, paddingHorizontal: 12, borderRadius: 8, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#0a0a0a', flexDirection: 'row', alignItems: 'center' },
	passwordInput: { flex: 1, paddingHorizontal: 0, paddingVertical: 0, borderWidth: 0, backgroundColor: 'transparent' },
	passwordToggle: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
	rememberAccessRow: { minHeight: 28, flexDirection: 'row', alignItems: 'center', gap: Spacing.two, justifyContent: 'flex-start' },
	rememberSwitch: { width: 30, height: 18, padding: 2, borderRadius: 50, justifyContent: 'center' },
	rememberSwitchOn: { backgroundColor: '#0a0a0a', alignItems: 'flex-end' },
	rememberSwitchOff: { backgroundColor: '#e1e1e1', alignItems: 'flex-start' },
	rememberSwitchThumb: { width: 14, height: 14, borderRadius: 50, backgroundColor: '#ffffff', shadowColor: '#0a0a0a', shadowOpacity: 0.16, shadowRadius: 2, shadowOffset: { width: 0, height: 1 }, elevation: 2 },
	rememberAccessText: { fontSize: 13 },
	rememberHelpButton: { width: 22, height: 22, alignItems: 'center', justifyContent: 'center', borderRadius: 50 },
	rememberHelpIcon: { width: 14, height: 14, borderWidth: 1, borderColor: '#8c8781', borderRadius: 8, fontSize: 11, lineHeight: 13, textAlign: 'center', fontWeight: '700' },
	readonly: { color: '#999' },
	select: { padding: Spacing.three, borderRadius: 8, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#0a0a0a', flexDirection: 'row', justifyContent: 'space-between' },
	genderDropdownIcon: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '90deg' }] },
	genderDropdownIconOpen: { transform: [{ rotate: '-90deg' }] },
	dropdown: { borderWidth: 1, borderColor: '#0a0a0a', borderRadius: 8, backgroundColor: '#fff' },
	option: { padding: Spacing.three, borderBottomWidth: 1, borderBottomColor: '#eee' },
	textButton: { display: 'none', alignItems: 'center', padding: Spacing.two },
	forgotButton: { alignSelf: 'flex-end' },
	linkText: { color: '#625d57', textDecorationLine: 'underline' },
	errorMessage: { color: '#ed6560', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 17 },
	linkTextAlert: { color: '#ed6560', fontSize: 11 },
	rememberHelpScreen: { flex: 1, backgroundColor: '#eeeeee' },
	rememberHelpSafeArea: { flex: 1, backgroundColor: '#eeeeee' },
	rememberHelpHeader: { minHeight: 58, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end' },
	rememberHelpHeaderSpacer: { flex: 1 },
	rememberHelpClose: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
	rememberHelpContent: { paddingHorizontal: 24, paddingTop: 8, paddingBottom: 32, gap: 12 },
	rememberHelpTitle: { color: '#ef4444', fontSize: 17, lineHeight: 23, fontWeight: '700' },
	rememberHelpBody: { fontSize: 12, lineHeight: 17 },
	authFooter: { flexDirection: 'row', gap: Spacing.two },
	authFooterButton: { flex: 1, minHeight: 48, justifyContent: 'center' },
	passwordRules: { gap: Spacing.one, paddingVertical: Spacing.one },
	passwordRule: { fontSize: 12, lineHeight: 17 },
	passwordRuleValid: { color: '#2f8f5b' },
	passwordRuleInvalid: { color: '#ed6560' },
	checkRow: { flexDirection: 'row', gap: Spacing.two, alignItems: 'center' },
	checkbox: { width: 18, height: 18, borderWidth: 1, borderColor: '#aaa', borderRadius: 4, alignItems: 'center', justifyContent: 'center' },
	checkboxMark: { color: '#ffffff', fontSize: 13, lineHeight: 16, fontWeight: '700' },
	resendButton: { padding: Spacing.four, borderRadius: 8, alignItems: 'center', backgroundColor: '#e7e3da' },
	resendText: { color: '#5d5955', fontWeight: '700' },
	checked: { backgroundColor: '#0a0a0a' },
	disabled: { opacity: 0.5 },
	notificationMessage: { color: '#ed6560', fontSize: 11, lineHeight: 16 },
  authTitle: { fontFamily: Fonts.bold, fontSize: 13, lineHeight: 16, fontWeight: '700', color: '#0a0a0a' },
	authSubtitleDesc: { fontFamily: Fonts.medium, fontSize: 12, lineHeight: 14, fontWeight: '400', color: '#0a0a0a' },
	authSubtitle: { fontFamily: Fonts.medium, fontSize: 13, lineHeight: 16, fontWeight: '400', color: '#0a0a0a' },
	authText: { fontFamily: Fonts.serif, fontSize: 13, lineHeight: 16, fontWeight: '500', color: '#0a0a0a' },
	authTextTipBold: { fontFamily: Fonts.bold, fontSize: 12, lineHeight: 16, fontWeight: '700', color: '#0a0a0a' },
	authTextTip: { fontFamily: Fonts.medium, fontSize: 12, lineHeight: 16, fontWeight: '400', color: '#0a0a0a' },
	registerCard: { gap: 10, padding: 14, borderRadius: 14 },
	registerTitle: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 16, lineHeight: 22, fontWeight: '700' },
	registerSubtitle: { color: '#4f4b47', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 18, fontWeight: '400' },
	registerInput: { minHeight: 42, paddingVertical: 8, borderRadius: 8 },
	registerMessage: { color: '#ed6560', fontSize: 11, lineHeight: 16 },
	registerButton: { minHeight: 46, marginTop: 2, marginBottom: 0, borderRadius: 8 },
	registerButtonText: { color: '#0a0a0a', fontFamily: Fonts.sans, fontSize: 13, lineHeight: 18, fontWeight: '500' },
	registerButtonTextDisabled: { color: '#9e9991' },
	privacyCreateLink: { fontFamily: Fonts.medium, fontSize: 13, lineHeight: 16, fontWeight: '500', color: '#0a0a0a', textDecorationLine: 'underline' },
  privacyLink: { color: '#0a0a0a', fontFamily: Fonts.sans, textDecorationLine: 'underline', fontSize: 12, lineHeight: 14, fontWeight: '400' },
	logoutDivider: { borderWidth: 0, borderColor: '#dedbd5' },
  accountTile: { minHeight: 96, flexDirection: 'column', justifyContent: 'space-between', alignItems: 'stretch' },
  tileHeader: { width: '100%', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  tileIcon: { width: 20, height: 20, alignItems: 'flex-start', justifyContent: 'flex-start' },
  tileLabel: { color: '#0a0a0a', fontSize: 13, lineHeight: 18 },
  preferenceLabel: { flexDirection: 'row', alignItems: 'center', gap: Spacing.two },
  preferenceText: { color: '#0a0a0a', fontSize: 14 },
  personalDataContent: { paddingTop: Spacing.three, paddingBottom: 70 },
  personalDataCard: { gap: 0, padding: 24, borderRadius: 16 },
  personalDataTitle: { marginBottom: 15, color: '#0a0a0a', fontFamily: Fonts.medium, fontSize: 20, lineHeight: 34, fontWeight: '500' },
  personalDataFields: { gap: 21 },
  personalDataField: { gap: 4 },
  personalDataLabel: { color: '#0a0a0a', fontFamily: Fonts.sans, fontSize: 14, lineHeight: 20, fontWeight: '400' },
  personalDataValue: { color: '#a29b93', fontFamily: Fonts.sans, fontSize: 14, lineHeight: 20, fontWeight: '400' },
  personalDataInput: { minHeight: 42, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: '#0a0a0a', backgroundColor: '#ffffff', color: '#0a0a0a', fontFamily: Fonts.sans, fontSize: 16, lineHeight: 20 },
  personalDataReadonlyInput: { borderColor: '#0a0a0a', backgroundColor: '#ebe8e5', color: '#a7a099' },
  personalDataSelect: { minHeight: 42, paddingHorizontal: 14, borderRadius: 8, borderWidth: 1, borderColor: '#0a0a0a', backgroundColor: '#ffffff', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  personalDataSelectText: { color: '#0a0a0a', fontFamily: Fonts.sans, fontSize: 16, lineHeight: 22, fontWeight: '400' },
  personalDataDropdown: { borderWidth: 1, borderColor: '#0a0a0a', borderRadius: 8, backgroundColor: '#ffffff' },
  personalDataOption: { paddingHorizontal: 14, paddingVertical: 8, borderBottomWidth: 0, borderBottomColor: '#eeeae5' },
  personalDataFeedback: { marginTop: 18, color: '#ed6560', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 17 },
  saveSuccessOverlay: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24, zIndex: 10 },
  saveSuccessToast: { maxWidth: '92%', paddingHorizontal: 22, paddingVertical: 14, borderRadius: 8, backgroundColor: '#358846', shadowColor: '#0a0a0a', shadowOpacity: 0.2, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 8 },
  saveSuccessText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600', textAlign: 'center' },
  personalDataEditSection: { marginTop: 28, paddingTop: 20, borderTopWidth: 1, borderTopColor: '#e8e3dd' },
  personalDataEditLink: { color: '#5d5850', fontFamily: Fonts.sans, fontSize: 14, lineHeight: 20, textDecorationLine: 'underline' },
  personalDataConfirmButton: { minHeight: 42, display: 'flex', justifyContent: 'center' , alignItems: 'center' },
});
