import { StyleSheet } from 'react-native';
import { Fonts, Spacing } from '@/constants/theme';
export const styles = StyleSheet.create({
  container: { flex: 1 },
  safeArea: { flex: 1, padding: Spacing.four },
  content: { gap: Spacing.two, paddingVertical: Spacing.two, paddingBottom: 170 },
  checkoutShelfTitle: { fontSize: 16, lineHeight: 20 },
  flex: { flex: 1 },
  emptyCartContent: { gap: Spacing.five, paddingTop: Spacing.three, paddingBottom: 170, marginTop: 40 },
  emptyCartMessage: { alignItems: 'center', gap: 16, paddingHorizontal: Spacing.three },
  emptyCartTitle: { fontFamily: Fonts.bold, fontSize: 16, lineHeight: 22, textAlign: 'center' },
  emptyCartDescription: { maxWidth: 300, fontFamily: Fonts.sans, fontSize: 12, lineHeight: 17, textAlign: 'center' },
  emptyCartShelfTitle: { fontSize: 16, lineHeight: 22 },
  pageTitle: { fontSize: 16, lineHeight: 21, fontFamily: Fonts.bold, fontWeight: '700' },
  card: { gap: 6, paddingVertical: 20, paddingHorizontal: 12, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#e6e1da'  },
  customerDataCard: { gap: 0, padding: 24, borderRadius: 16 },
  customerDataTitle: { marginBottom: 28, color: '#0a0a0a', fontFamily: Fonts.medium, fontSize: 26, lineHeight: 34, fontWeight: '500' },
  customerDataDescription: { marginBottom: 24, color: '#0a0a0a', fontFamily: Fonts.sans, fontSize: 13, lineHeight: 20, fontWeight: '400' },
  customerDataRows: { gap: 21 },
  customerDataRow: { gap: 4 },
  customerDataLabel: { color: '#0a0a0a', fontFamily: Fonts.sans, fontSize: 14, lineHeight: 20, fontWeight: '400' },
  customerDataValue: { color: '#a29b93', fontFamily: Fonts.sans, fontSize: 17, lineHeight: 24, fontWeight: '400' },
  customerDataEditSection: { marginTop: 28, paddingTop: 20, borderTopWidth: 1, borderTopColor: '#e8e3dd' },
  customerDataEditLink: { color: '#5d5852', fontFamily: Fonts.sans, fontSize: 16, lineHeight: 22, textDecorationLine: 'underline' },
  customerEditCard: { gap: 0, padding: 24, borderRadius: 16 },
  customerEditFields: { gap: 18 },
  personalField: { gap: 6 },
  personalFieldLabel: { color: '#0a0a0a', fontFamily: Fonts.sans, fontSize: 14, lineHeight: 20, fontWeight: '400' },
  personalInput: { minHeight: 50, paddingHorizontal: 14, paddingVertical: 12, borderRadius: 8, borderWidth: 1, borderColor: '#0a0a0a', backgroundColor: '#ffffff', color: '#45413d', fontFamily: Fonts.sans, fontSize: 16, lineHeight: 22 },
  personalDataSelect: { minHeight: 50, paddingHorizontal: 14, borderRadius: 8, borderWidth: 1, borderColor: '#0a0a0a', backgroundColor: '#ffffff', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  personalDataSelectText: { color: '#45413d', fontFamily: Fonts.sans, fontSize: 16, lineHeight: 22, fontWeight: '400' },
  personalDataDropdown: { borderWidth: 1, borderColor: '#d9d3cc', borderRadius: 8, backgroundColor: '#ffffff' },
  personalDataOption: { paddingHorizontal: 14, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#eeeae5' },
  customerReviewData: { gap: 2, marginTop: 1, marginBottom: 2 },
  customerReviewValue: { color: '#0a0a0a', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 18 },
  cardTitle: { fontSize: 15, lineHeight: 20, fontFamily: Fonts.bold, fontWeight: '700' },
  sectionTitle: { fontFamily: Fonts.bold, fontSize: 12, lineHeight: 17, fontWeight: '700' },
  bodyText: { fontFamily: Fonts.sans, fontSize: 12, lineHeight: 20, fontWeight: '400' },
  productsCard: { padding: 12, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#e6e1da' },
  productBlock: { paddingVertical: Spacing.one },
  productDivider: { marginTop: Spacing.two, paddingTop: Spacing.three, borderTopWidth: 1, borderTopColor: '#ece8e2' },
  itemRow: { flexDirection: 'row', alignItems: 'stretch', gap: Spacing.three },
  itemImage: { width: '25%', maxWidth: 142, aspectRatio: 0.76, borderRadius: 8, backgroundColor: '#e8e8ea' },
  itemDetails: { flex: 1, minWidth: 0, justifyContent: 'space-between', gap: Spacing.two },
  itemTopRow: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.one },
  itemName: { flex: 1, minWidth: 0, fontFamily: Fonts.sans, fontSize: 14, lineHeight: 20, fontWeight: '400' },
  itemBottomRow: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: Spacing.two },
  itemPrice: { flexShrink: 0, fontFamily: Fonts.sans, fontSize: 15, lineHeight: 20, fontWeight: '600' },
  quantityControl: { minHeight: 34, flexDirection: 'row', alignItems: 'center', borderRadius: 9, borderWidth: 1, borderColor: '#cfc8bf', overflow: 'hidden' },
  quantityButton: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center' },
  quantityValue: { minWidth: 42, height: 34, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  quantityCount: { minWidth: 14, textAlign: 'center' },
  removeButton: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
  giftRow: { marginTop: Spacing.three, paddingTop: Spacing.three, borderTopWidth: 1, borderTopColor: '#ece8e2', flexDirection: 'row', alignItems: 'center', gap: Spacing.two },
  giftCheckbox: { width: 16, height: 16, borderRadius: 4, borderWidth: 1, borderColor: '#aaa49c', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  giftCheckboxSelected: { borderColor: '#0a0a0a', backgroundColor: '#0a0a0a' },
  giftCheck: { color: '#FFFFFF', fontSize: 11, lineHeight: 15 },
  giftText: { flex: 1, fontSize: 11 },
  giftMessage: { padding: Spacing.three, borderRadius: 4, borderWidth: 1, borderColor: '#e5c95a', backgroundColor: '#fffbe7' },
  giftMessageText: { color: '#9a7b2f', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 18 },
  field: { flex: 1, gap: 4 },
  fieldLabel: { fontFamily: Fonts.sans, fontSize: 12, lineHeight: 17, fontWeight: '400' },
  inputWrap: { position: 'relative' },
  input: { minHeight: 46, paddingHorizontal: 12, borderRadius: 8, borderWidth: 1, borderColor: '#d9d3cc', backgroundColor: '#FFFFFF', fontFamily: Fonts.sans, fontSize: 15, color: '#0a0a0a' },
  appliedCouponInput: { fontFamily: Fonts.bold, fontWeight: '700', textTransform: 'uppercase' },
  inputWithAccessory: { paddingRight: 62 },
  fieldAccessory: { position: 'absolute', right: 8, top: 9, width: 42, height: 27, alignItems: 'center', justifyContent: 'center' },
  inputError: { borderColor: '#ff7772', borderWidth: 1.5 },
  errorText: { color: '#ed6560', fontSize: 11, lineHeight: 15, fontFamily: Fonts.sans },
  successText: { color: '#2f8f5b', fontSize: 12, fontFamily: Fonts.sans },
  couponSuccess: { color: '#2f8f5b', fontFamily: Fonts.sans, fontSize: 13, lineHeight: 18 },
  couponError: { color: '#ed6560', fontFamily: Fonts.sans, fontSize: 13, lineHeight: 18 },
  inline: { flexDirection: 'row', gap: Spacing.two, alignItems: 'flex-start' },
  select: { minHeight: 46, paddingHorizontal: 12, borderRadius: 8, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#d9d3cc', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  selectArrow: { fontSize: 20, color: '#625d57', lineHeight: 22 },
  dropdownIcon: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '90deg' }] },
  dropdownIconOpen: { transform: [{ rotate: '-90deg' }] },
  dropdown: { borderWidth: 1, borderColor: '#d9d3cc', borderRadius: 8, backgroundColor: '#FFFFFF' },
  option: { gap: 4, padding: Spacing.three, borderRadius: 8, borderBottomWidth: 1, borderColor: '#d9d3cc', backgroundColor: '#FFFFFF' },
  addressList: { gap: Spacing.two, marginTop: Spacing.two },
  addressOption: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.two, padding: Spacing.two, borderRadius: 8, borderWidth: 1, borderColor: '#d9d3cc', backgroundColor: '#ffffff' },
  addressOptionSelected: { borderColor: '#0a0a0a', borderWidth: 2 },
  addressDetails: { flex: 1, gap: 2 },
  addressSummaryHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.two },
  addressSummaryTitleRow: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: Spacing.two },
  addressSummaryTitle: { flex: 1, fontFamily: Fonts.bold, fontSize: 13, lineHeight: 18, fontWeight: '700' },
  addressDivider: { height: 1, backgroundColor: '#eeeae5' },
  dataLabel: { fontFamily: Fonts.sans, fontSize: 12, lineHeight: 17, fontWeight: '600' },
  link: { color: '#4f4b47', textDecorationLine: 'underline', fontSize: 11, lineHeight: 15, fontFamily: Fonts.sans },
  primary: { minHeight: 48, padding: Spacing.four, paddingHorizontal: 20, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0a0a0a' },
  secondary: { minHeight: 48, padding: Spacing.three, borderRadius: 8, borderWidth: 1, borderColor: '#0a0a0a', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  secondaryText: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 14, fontWeight: '700' },
  fixedFooter: { position: 'absolute', left: 0, right: 0, bottom: 0, gap: Spacing.two, padding: Spacing.two, paddingTop: 10, paddingBottom: 35, backgroundColor: '#ffffff' },
  orderSuccessSafeArea: { flex: 1, paddingHorizontal: Spacing.four },
  orderSuccessHeader: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#f0ede8' },
  orderSuccessContent: { gap: Spacing.three, paddingTop: Spacing.three, paddingBottom: Spacing.five },
  orderSuccessMessageCard: { alignItems: 'center', gap: Spacing.two, paddingHorizontal: Spacing.four, paddingVertical: 24, borderRadius: 16, borderWidth: 1, borderColor: '#e6e1da', backgroundColor: '#FFFFFF' },
  orderSuccessDetailsCard: { gap: Spacing.two, padding: Spacing.three, borderRadius: 16, borderWidth: 1, borderColor: '#e6e1da', backgroundColor: '#FFFFFF' },
  orderSuccessIcon: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#a9d9bd', backgroundColor: '#f3fbf5' },
  orderSuccessCheck: { color: '#2f8f5b', fontFamily: Fonts.bold, fontSize: 23, lineHeight: 28, fontWeight: '700' },
  orderSuccessTitle: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 17, lineHeight: 23, fontWeight: '700', textAlign: 'center' },
  orderSuccessDescription: { color: '#4f4b47', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 19, textAlign: 'center' },
  orderSuccessSectionTitle: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 14, lineHeight: 19, fontWeight: '700' },
  orderSuccessId: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 16, lineHeight: 22, fontWeight: '700' },
  orderSuccessMeta: { color: '#8a857f', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 18 },
  orderSuccessOrdersButton: { minHeight: 42, marginTop: Spacing.one, borderRadius: 8, borderWidth: 1.5, borderColor: '#0a0a0a', alignItems: 'center', justifyContent: 'center' },
  orderSuccessOrdersButtonText: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 12, lineHeight: 17, fontWeight: '700' },
  orderSuccessDivider: { height: 1, marginVertical: Spacing.two, backgroundColor: '#eeeae5' },
  orderSuccessSectionHeader: { flexDirection: 'row', alignItems: 'center', gap: Spacing.two },
  orderSuccessInfoList: { gap: 2 },
  orderSuccessInfo: { color: '#5f5a55', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 18 },
  orderSuccessHomeButton: { minHeight: 46, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0a0a0a' },
  orderSuccessHomeButtonText: { color: '#FFFFFF', fontFamily: Fonts.bold, fontSize: 12, lineHeight: 17, fontWeight: '700' },
  smallButton: { minHeight: 46, paddingHorizontal: 14, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0a0a0a' },
  buttonText: { color: '#FFFFFF', fontFamily: Fonts.bold, fontSize: 13, fontWeight: '700' },
  selected: { borderColor: '#0a0a0a', borderWidth: 2 },
  selectedAddressCard: { gap: Spacing.two },
  shippingCard: { gap: Spacing.two, padding: 12, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#e6e1da' },
  shippingAddressRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.two },
  pinIcon: { fontSize: 22, color: '#0a0a0a' },
  shippingAddressText: { flex: 1, fontFamily: Fonts.sans, fontSize: 14, lineHeight: 20, fontWeight: '400' },
  shippingSection: { gap: Spacing.two },
  shippingOption: { flexDirection: 'row', alignItems: 'center', gap: Spacing.two, padding: Spacing.two, borderRadius: 8, borderWidth: 1, borderColor: '#b0a69b', backgroundColor: '#FFFFFF' },
  shippingOptionSelected: { borderColor: '#0a0a0a', borderWidth: 2 },
  shippingOptionDetails: { flex: 1, gap: 2 },
  pickupButton: { flexDirection: 'row', alignItems: 'center', gap: Spacing.two, padding: Spacing.two, borderRadius: 8, borderWidth: 1, borderColor: '#b0a69b', backgroundColor: '#FFFFFF' },
  pickupSelectedCard: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.two, padding: Spacing.two, borderRadius: 8, backgroundColor: '#FFFFFF' },
  pickupStoreCard: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.two, padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#b0a69b', backgroundColor: '#FFFFFF' },
  pickupStoreName: { fontFamily: Fonts.bold, fontSize: 13, lineHeight: 18, fontWeight: '700' },
  radio: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: '#b0a69b', alignItems: 'center', justifyContent: 'center' },
  radioSelected: { borderColor: '#0a0a0a' },
  radioDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#0a0a0a' },
  summaryCard: { paddingVertical: 16 },
  summaryTitle: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 14, lineHeight: 19, fontWeight: '700' },
  summary: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 1 },
  summaryTotal: { marginTop: 4, paddingTop: 10, borderTopWidth: 1, borderTopColor: '#eeeae5' },
  progressCard: { gap: 8, padding: Spacing.two, borderRadius: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#fff' },
  progressLabel: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.one },
  progressTrack: { height: 6, borderRadius: 3, overflow: 'hidden', backgroundColor: '#e3ded5' },
  progressFill: { height: 6, borderRadius: 3, backgroundColor: '#2f8f5b' },
  giftCardSection: { gap: Spacing.two },
  giftCardNotice: { minHeight: 40, justifyContent: 'center', paddingHorizontal: Spacing.three, borderRadius: 8, backgroundColor: '#0a0a0a' },
  giftCardNoticeText: { color: '#FFFFFF', fontSize: 11, lineHeight: 16, textDecorationLine: 'underline', textAlign: 'center' },
  giftCardLookup: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.two, padding: Spacing.two, borderRadius: 8, backgroundColor: '#f8f6f2' },
  availableGiftCardsCard: { gap: Spacing.two, padding: 12, borderRadius: 16, borderWidth: 1, borderColor: '#e6e1da', backgroundColor: '#FFFFFF' },
  availableGiftCardRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.two, paddingTop: Spacing.two, borderTopWidth: 1, borderTopColor: '#ece8e2' },
  paymentCard: { gap: 6, padding: 12, borderRadius: 16, borderWidth: 1, borderColor: '#e6e1da', backgroundColor: '#FFFFFF' },
  paymentCardSelected: { borderColor: '#0a0a0a', borderWidth: 2 },
  paymentHeader: { minHeight: 28, flexDirection: 'row', alignItems: 'center', gap: Spacing.two, justifyContent: 'space-between' },
  paymentDivider: { height: 1, backgroundColor: '#eeeae5' },
  giftCardRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.two, paddingTop: Spacing.one },
  giftCardDetails: { flex: 1, gap: 1 },
  giftCardCode: { color: '#0a0a0a', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 18 },
  giftCardAmount: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  giftCardRemove: { color: '#4a82e8', fontFamily: Fonts.bold, fontSize: 11, lineHeight: 15, fontWeight: '700' },
  giftCardRemaining: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 13, lineHeight: 20, fontWeight: '700' },
  giftCardContinueButton: { minHeight: 48, marginTop: Spacing.one, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0a0a0a' },
  giftCardButtonDisabled: { opacity: 0.5 },
  pixInfo: { gap: Spacing.two, marginTop: Spacing.one, padding: Spacing.three, borderRadius: 8, backgroundColor: '#f5f5f5' },
  pixQrImage: { alignSelf: 'center', width: 240, height: 240, marginVertical: Spacing.two },
  pixCodeInput: { minHeight: 92, textAlignVertical: 'top' },
  pixScreen: { flex: 1, position: 'relative' },
  pixContent: { gap: Spacing.three, paddingHorizontal: Spacing.one, paddingTop: Spacing.three, paddingBottom: Spacing.six },
  pixBrandHeader: { alignItems: 'center', gap: Spacing.one, paddingVertical: Spacing.one },
  pixBrandTitle: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 15, lineHeight: 20 },
  pixInfoCard: { minHeight: 50, flexDirection: 'row', alignItems: 'center', gap: Spacing.two, paddingHorizontal: Spacing.three, borderRadius: 8, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#f0ece8' },
  pixInfoIcon: { color: '#8b746b', fontSize: 22, lineHeight: 24 },
  pixInfoText: { flex: 1, color: '#0a0a0a', fontFamily: Fonts.sans, fontSize: 14, lineHeight: 20 },
  pixValueCard: { minHeight: 54, flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.three, borderRadius: 8, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#f0ece8' },
  pixValueLabel: { color: '#77736f', fontFamily: Fonts.sans, fontSize: 14, lineHeight: 20 },
  pixValue: { marginLeft: 4, color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 14, lineHeight: 20 },
  pixCodeCard: { gap: Spacing.two, padding: Spacing.three, borderRadius: 8, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#f0ece8' },
  pixSectionTitle: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 15, lineHeight: 20, fontWeight: '700' },
  pixCodeField: { minHeight: 44, paddingHorizontal: Spacing.two, borderRadius: 6, backgroundColor: '#fafafa', color: '#77736f', fontFamily: Fonts.mono, fontSize: 12, textAlignVertical: 'center' },
  pixCodePlaceholder: { color: '#9a9692', fontFamily: Fonts.sans },
  pixActionRow: { flexDirection: 'row', gap: Spacing.two },
  pixActionButton: { flex: 1, minHeight: 46, paddingHorizontal: Spacing.two, borderRadius: 7, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0a0a0a' },
  pixQrToggle: { flex: 0, alignSelf: 'stretch' },
  pixActionButtonDisabled: { opacity: 0.45 },
  pixActionText: { color: '#FFFFFF', fontFamily: Fonts.bold, fontSize: 13, lineHeight: 18, fontWeight: '700' },
  pixQrCard: { alignSelf: 'center', padding: Spacing.three, borderRadius: 8, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#f0ece8', elevation: 4 },
  pixInstructionsCard: { gap: Spacing.one, padding: Spacing.three, borderRadius: 8, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#f0ece8' },
  pixInstruction: { color: '#77736f', fontFamily: Fonts.sans, fontSize: 14, lineHeight: 22 },
  pixTimer: { color: '#77736f', fontFamily: Fonts.sans, fontSize: 13, lineHeight: 18, textAlign: 'center' },
  pixConfirmationText: { paddingHorizontal: Spacing.five, color: '#8d8985', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  pixToast: { position: 'absolute', left: Spacing.one, right: Spacing.one, bottom: Spacing.two, minHeight: 48, flexDirection: 'row', alignItems: 'center', paddingLeft: Spacing.three, paddingRight: Spacing.one, borderRadius: 8, backgroundColor: '#53c76b', elevation: 5, zIndex: 10 },
  pixToastCheck: { color: '#FFFFFF', fontFamily: Fonts.bold, fontSize: 18, lineHeight: 22 },
  pixToastText: { flex: 1, marginLeft: Spacing.two, color: '#FFFFFF', fontFamily: Fonts.medium, fontSize: 14, lineHeight: 20 },
  pixToastClose: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
  pixToastCloseText: { color: '#FFFFFF', fontFamily: Fonts.sans, fontSize: 22, lineHeight: 24 },
  creditCardVisual: { minHeight: 168, padding: Spacing.three, borderRadius: 8, overflow: 'hidden', justifyContent: 'space-between', gap: Spacing.two },
  creditCardVisualCompact: { width: '100%', height: 'auto', maxWidth: 340, alignSelf: 'center', padding: Spacing.three, borderRadius: 8, gap: Spacing.one },
  creditCardVisualTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  creditCardLabel: { color: '#dfe5ee', fontSize: 12, fontFamily: Fonts.sans },
  creditCardHint: { color: 'rgba(255,255,255,0.62)', fontSize: 9, lineHeight: 13, fontFamily: Fonts.sans },
  creditCardNumberBlock: { gap: 2 },
  creditCardNumber: { color: '#FFFFFF', fontSize: 20, lineHeight: 26, letterSpacing: 1, fontFamily: Fonts.sans },
  creditCardNumberCompact: { fontSize: 16, lineHeight: 20, letterSpacing: 0.5 },
  creditCardDataRow: { flexDirection: 'row', alignItems: 'flex-end', gap: Spacing.two },
  creditCardDataPrimary: { flex: 1, minWidth: 0, gap: 2 },
  creditCardData: { minWidth: 47, gap: 2 },
  creditCardMeta: { color: '#e3e8ef', fontSize: 11, lineHeight: 15, fontFamily: Fonts.sans },
  billingRow: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.two },
  billingCheckbox: { width: 20, height: 20, borderRadius: 5, backgroundColor: '#0a0a0a', alignItems: 'center', justifyContent: 'center' },
  billingCheck: { color: '#FFFFFF', fontSize: 14, lineHeight: 17 },
  billingText: { flex: 1, fontSize: 13, lineHeight: 18 },
  acceptedBrands: { gap: Spacing.two },
  acceptedTitle: { fontSize: 13, color: '#625d57', fontFamily: Fonts.sans },
  brandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 7 },
  reviewHeader: { flexDirection: 'row', alignItems: 'center', gap: Spacing.one },
  reviewDeliveryTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  freeText: { color: '#2f9b62', fontFamily: Fonts.sans, fontSize: 13 },
  deliveryText: { color: '#2f9b62', fontFamily: Fonts.sans, fontSize: 12 },
  reviewAddress: { gap: 2, marginTop: Spacing.one, padding: Spacing.two, borderRadius: 8, backgroundColor: '#f8f8f8' },
  reviewItemsSection: { gap: Spacing.two, marginTop: Spacing.two },
  reviewItemsToggle: { minHeight: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.two },
  reviewItemsToggleLabel: { color: '#4f4b47', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 17, textDecorationLine: 'underline' },
  reviewItemsChevron: { width: 22, height: 22, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '90deg' }] },
  reviewItemsChevronExpanded: { transform: [{ rotate: '-90deg' }] },
  reviewItemsPreview: { gap: 6, paddingRight: Spacing.two },
  reviewItemPreview: { width: 58, height: 78, borderRadius: 3, overflow: 'hidden', backgroundColor: '#eeeae5' },
  reviewItemPreviewImage: { width: '100%', height: '100%', backgroundColor: '#eeeae5' },
  reviewItemsExpanded: { gap: Spacing.two },
  reviewItem: { flexDirection: 'row', alignItems: 'stretch', gap: Spacing.three },
  reviewItemImage: { width: 50, height: 70, aspectRatio: 3/4, borderRadius: 8, backgroundColor: '#eeeae5' },
  reviewItemDetails: { flex: 1, minWidth: 0, justifyContent: 'center', gap: 4 },
  reviewItemName: { fontFamily: Fonts.sans, fontSize: 13, lineHeight: 18, fontWeight: '400' },
  reviewItemQuantity: { color: '#0a0a0a', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 17, fontWeight: '400' },
  reviewItemPrice: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 12, lineHeight: 17, fontWeight: '700' },
  paymentReview: { alignItems: 'center', gap: Spacing.one, paddingVertical: Spacing.two },
  paymentReviewCard: { width: '100%', gap: Spacing.two, alignItems: 'center' },
  pixRemainingSummary: { alignItems: 'center', gap: 2, paddingTop: Spacing.one },
  pixRemainingLabel: { color: '#77736f', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 16 },
  pixRemainingValue: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 14, lineHeight: 19, fontWeight: '700' },
  giftCardReview: { width: '100%', gap: Spacing.two, alignItems: 'stretch' },
  giftCardReviewTitle: { color: '#0a0a0a', fontFamily: Fonts.sans, fontSize: 13, lineHeight: 20 },
  giftCardReviewRow: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.two, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two, borderRadius: 4, backgroundColor: '#f8f8f8' },
  giftCardReviewColumn: { gap: 1, flexShrink: 1 },
  giftCardReviewColumnRight: { alignItems: 'flex-end' },
  giftCardReviewLabel: { color: '#77736f', fontFamily: Fonts.sans, fontSize: 11, lineHeight: 15 },
  giftCardReviewCode: { color: '#0a0a0a', fontFamily: Fonts.mono, fontSize: 13, lineHeight: 18 },
  giftCardReviewValue: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 13, lineHeight: 18, fontWeight: '700' },
  installmentSummary: { width: 'auto', alignSelf: 'center', alignItems: 'center', gap: 2, padding: Spacing.two, borderRadius: 8, backgroundColor: '#FFFFFF' },
  installmentSummaryLabel: { color: '#77736f', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 16 },
  installmentSummaryValue: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 14, lineHeight: 19 },
  installmentsContent: { gap: Spacing.three, paddingVertical: Spacing.three, paddingBottom: Spacing.five },
  installmentCardHeader: { minHeight: 60, flexDirection: 'row', alignItems: 'center', gap: Spacing.two, padding: Spacing.two, borderRadius: 8, borderWidth: 1, borderColor: '#e6e1da', backgroundColor: '#FFFFFF' },
  installmentCardName: { flex: 1, fontFamily: Fonts.bold, fontSize: 14, lineHeight: 20 },
  installmentList: { gap: Spacing.two },
  installmentOption: { minHeight: 64, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.two, paddingHorizontal: Spacing.two, paddingVertical: Spacing.three, borderRadius: 8, borderWidth: 1, borderColor: '#e6e1da', backgroundColor: '#FFFFFF' },
  installmentOptionText: { flex: 1, gap: 2 },
  installmentCount: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 15, lineHeight: 20 },
  installmentInterest: { color: '#77736f', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 16 },
  installmentOptionRight: { flexDirection: 'row', alignItems: 'center', gap: Spacing.two },
  installmentTotal: { color: '#77736f', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 16 },
  modalOverlay: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: Spacing.five, backgroundColor: 'rgba(0, 0, 0, 0.62)' },
  modalCard: { width: '100%', maxWidth: 340, gap: Spacing.two, padding: 16, borderRadius: 8, backgroundColor: '#FFFFFF' },
  modalTitle: { textAlign: 'center', lineHeight: 26, fontSize: 16, marginBottom: Spacing.two, fontFamily: Fonts.medium, fontWeight: '500' },
	modalTitleProduct: {fontFamily: Fonts.bold, fontWeight: '700', lineHeight: 26, fontSize: 16},
  modalDeleteButton: { minHeight: 48, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0a0a0a' },
  modalCancelButton: { minHeight: 48, borderRadius: 8, borderWidth: 1, borderColor: '#0a0a0a', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  giftCardIdentityKeyboard: { width: '100%', maxWidth: 420, maxHeight: '90%' },
  giftCardIdentityOverlay: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: Spacing.three, paddingVertical: Spacing.five, backgroundColor: 'rgba(0, 0, 0, 0.62)' },
  giftCardIdentityModalCard: { width: '100%', maxHeight: '100%', padding: 15, borderRadius: 8, backgroundColor: '#FFFFFF' },
  giftCardIdentityScroll: { width: '100%', flexGrow: 0, flexShrink: 1 },
  giftCardIdentityModalContent: { gap: Spacing.two, paddingBottom: Spacing.one },
  giftCardIdentityHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.two },
  giftCardIdentityTitle: { flex: 1, minWidth: 0, fontFamily: Fonts.bold, fontSize: 16, lineHeight: 23, fontWeight: '700' },
  giftCardIdentityClose: { width: 20, height: 20, alignItems: 'center', justifyContent: 'center' },
  giftCardIdentityCloseText: { color: '#0a0a0a', fontSize: 20, lineHeight: 20 },
  giftCardIdentityField: { flex: 0, flexGrow: 0, flexShrink: 0, width: '100%' },
  giftCardIdentityInput: { width: '100%' },
  giftCardIdentityPasswordWrap: { position: 'relative', width: '100%' },
  giftCardIdentityPasswordInput: { paddingRight: 48 },
  giftCardIdentityPasswordToggle: { position: 'absolute', right: 8, top: 7, width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  giftCardIdentityPrimary: { minHeight: 48, alignSelf: 'stretch', paddingHorizontal: Spacing.two, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0a0a0a' },
  giftCardIdentityPrimaryInRow: { flex: 1, minWidth: 0 },
  giftCardIdentityCancelButton: { minWidth: 96, paddingHorizontal: Spacing.three },
  giftCardIdentityActionRow: { width: '100%', flexDirection: 'row', gap: Spacing.two, alignItems: 'stretch' },
  giftCardIdentityLinkButton: { alignSelf: 'center', paddingHorizontal: Spacing.one },
});
