import { StyleSheet } from 'react-native';
import { Fonts, Spacing } from '@/constants/theme';
import { DESCRIPTION_LINE_HEIGHT, DESCRIPTION_PREVIEW_LINES } from '@/constants/product-detail';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  safeArea: { flex: 1, position: 'relative' },
  header: { position: 'absolute', top: 0, left: 0, right: 0, paddingHorizontal: Spacing.three, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', zIndex: 20, elevation: 0 },
  heroHeader: { borderBottomWidth: 0, backgroundColor: 'transparent' },
  scrolledHeader: { borderBottomWidth: 1, borderBottomColor: '#ece8e2', backgroundColor: '#ffffff' },
  headerSide: { width: 102, flexDirection: 'row', alignItems: 'center' },
  headerActions: { justifyContent: 'flex-end', gap: 0 },
  headerButton: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center' },
  heroHeaderButton: { borderRadius: 20, backgroundColor: 'rgba(255, 255, 255, 0.62)' },
  logoButton: { minWidth: 90, minHeight: 38, alignItems: 'center', justifyContent: 'center' },
  logoPlaceholder: { minWidth: 90, minHeight: 38 },
  loader: { marginTop: Spacing.five },
  errorState: { flex: 1, alignItems: 'center', paddingHorizontal: Spacing.five, paddingTop: 132 },
  errorTitle: { fontSize: 21, lineHeight: 28, fontFamily: Fonts.semibold, fontWeight: '600', textAlign: 'center' },
  errorDescription: { maxWidth: 340, marginTop: Spacing.two, color: '#ed6560', fontSize: 14, lineHeight: 21, textAlign: 'center' },
  errorActions: { width: '100%', maxWidth: 340, gap: Spacing.two, marginTop: Spacing.five },
  errorPrimaryButton: { minHeight: 48, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0a0a0a' },
  errorPrimaryText: { color: '#FFFFFF', fontFamily: Fonts.bold, fontSize: 14, fontWeight: '700' },
  errorSecondaryButton: { minHeight: 48, borderRadius: 8, borderWidth: 1, borderColor: '#0a0a0a', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  errorSecondaryText: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 14, fontWeight: '700' },
  content: { paddingBottom: Spacing.five },
  contentWithFloating: { paddingBottom: 120 },
  galleryArea: { position: 'relative', backgroundColor: '#e8e8ea' },
  heroImagePressable: { flex: 1 },
  mainImage: { backgroundColor: '#e8e8ea' },
  heroShade: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 190 },
  heroDots: { position: 'absolute', left: Spacing.four, bottom: 85, flexDirection: 'row', alignItems: 'center', gap: 5 },
  heroProductInfo: { position: 'absolute', left: Spacing.four, right: Spacing.four, bottom: 18 },
  heroProductRow: { flexDirection: 'row', alignItems: 'flex-end', gap: Spacing.three },
  heroProductCopy: { flex: 1, gap: 3 },
  heroProductName: { maxWidth: 250, color: '#FFFFFF', fontSize: 12, lineHeight: 16 },
  heroProductPrice: { color: '#FFFFFF', fontSize: 12 },
  heroBuyButton: { minWidth: 96, minHeight: 40, paddingHorizontal: Spacing.three, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  heroBuyButtonText: { color: '#0a0a0a' },
	provadorVirtual: { fontSize: 12, fontFamily: Fonts.medium, fontWeight: '500' },
  viewer: { flex: 1, backgroundColor: '#fff' },
  viewerList: { flex: 1, backgroundColor: '#fff' },
  viewerListContent: { backgroundColor: '#fff' },
  viewerPage: { alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  viewerImage: { backgroundColor: '#fff' },
  viewerTopBar: { position: 'absolute', top: 0, left: 0, right: 0, paddingHorizontal: Spacing.four, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', zIndex: 5 },
  viewerCounter: { minWidth: 48, height: 36, paddingHorizontal: Spacing.three, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0, 0, 0, 0.34)' },
  viewerClose: { width: 35, height: 35, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0, 0, 0, 0.34)' },
  viewerText: { color: '#FFFFFF', fontSize: 14, lineHeight: 16, fontWeight: '600' },
  viewerCloseText: { color: '#FFFFFF', fontSize: 20, fontWeight: '400' },
  viewerDots: { position: 'absolute', left: 0, right: 0, bottom: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, zIndex: 5 },
  details: { gap: Spacing.four, padding: Spacing.four, backgroundColor: '#FFFFFF' },
  productHeading: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.three },
  headingText: { flex: 1, gap: 4 },
  productName: { fontSize: 14, lineHeight: 18, fontFamily: Fonts.medium, fontWeight: '400' },
  productMeta: { color: '#0a0a0a', fontFamily: Fonts.bold, fontSize: 10, lineHeight: 14, textTransform: 'uppercase' , marginVertical: 5 },
  favoriteButton: { width: 26, height: 26, alignItems: 'center', justifyContent: 'center' },
	listPriceContainer: {paddingVertical: 0, backgroundColor: '#ffffff' },
	listPriceRow: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  listPrice: { color: '#0a0a0a', fontSize: 13, lineHeight: 16 },
  listPriceValue: { color: '#0a0a0a', textDecorationLine: 'line-through' },
  discountPercentage: { color: '#0a0a0a', fontSize: 11 },
  priceRow: { flexDirection: 'row', alignItems: 'baseline', flexWrap: 'wrap', gap: Spacing.two },
	bestPrice: { color: '#0a0a0a', fontSize: 18, lineHeight: 18 },
  installmentText: { color: '#0a0a0a', fontFamily: Fonts.sans, fontSize: 12, lineHeight: 16 },
  selectorGroup: { gap: Spacing.two },
	selectorGroupVariant: { fontSize: 12 },
  colorList: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: Spacing.two },
  colorOption: { width: 30, height: 30, borderRadius: 50, borderWidth: 1, borderColor: '#ddd', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  selectedColorOption: { borderWidth: 1, borderColor: '#0a0a0a' },
  colorCircle: { width: 20, height: 20, borderRadius: 50, borderWidth: 1, borderColor: '#ddd' },
  moreColorsButton: { minHeight: 38, paddingHorizontal: Spacing.three, borderRadius: 50, borderWidth: 1, borderColor: '#0a0a0a', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  moreColorsText: { fontSize: 12},
	nameTitleColor: { fontSize: 12, fontFamily: Fonts.medium, fontWeight: '500' },
	nameColor: { fontSize: 12, fontFamily: Fonts.bold, fontWeight: '600'  },
	titleColorModal: { fontSize: 16 },
  variantOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.two },
  variantOption: { minWidth: 35, height: 35, paddingHorizontal: Spacing.two, borderRadius: 50, borderWidth: 1, borderColor: '#0a0a0a', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  variantOptionText: { fontSize: 12, lineHeight: 16 },
  selectedVariant: { backgroundColor: '#0a0a0a', borderColor: '#0a0a0a' },
  selectedVariantText: { color: '#FFFFFF', fontWeight: '700' },
  unavailableVariant: { opacity: 0.35, backgroundColor: '#eeeae4' },
  unavailableVariantText: { textDecorationLine: 'line-through' },
  selectionMessage: { marginTop: -Spacing.two, color: '#ed6560', fontWeight: '600' },
  hiddenMainAddButton: { display: 'none' },
  mainAddButton: { minHeight: 50, borderRadius: 8, flexDirection: 'row', gap: Spacing.two, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0a0a0a' },
  mainAddText: { color: '#FFFFFF', fontWeight: '700' },
  disabled: { opacity: 0.45 },
  messageText: { color: '#ed6560' },
  helperButtons: { flexDirection: 'row', gap: Spacing.two, paddingVertical: 10},
  helperButton: { flex: 1, paddingVertical: 8, paddingHorizontal: 10, borderRadius: 8, borderWidth: 1, borderColor: '#0a0a0a', flexDirection: 'row', gap: Spacing.one, alignItems: 'center', justifyContent: 'flex-start', backgroundColor: '#FFFFFF' },
  shippingSection: { gap: 8, paddingTop: Spacing.two },
  sectionTitle: { fontSize: 13, lineHeight: 16 },
  shippingRow: { minHeight: 32, flexDirection: 'row' },
  shippingInputWrap: { flex: 1, position: 'relative' },
  shippingInput: { width: '100%', paddingHorizontal: Spacing.three, paddingRight: 42, borderWidth: 1, borderColor: '#0a0a0a', borderTopLeftRadius: 8, borderBottomLeftRadius: 8, backgroundColor: '#FFFFFF', fontFamily: Fonts.sans },
  shippingClearButton: { position: 'absolute', top: 0, right: 2, bottom: 0, width: 34, alignItems: 'center', justifyContent: 'center' },
  shippingButton: { minWidth: 108, paddingHorizontal: Spacing.three, alignItems: 'center', justifyContent: 'center', borderTopRightRadius: 8, borderBottomRightRadius: 8, backgroundColor: '#0a0a0a' },
  shippingButtonText: { color: '#FFFFFF', fontWeight: '700' },
  shippingOptions: { overflow: 'hidden', backgroundColor: '#FFFFFF' },
  shippingQuotesList: { position: 'relative', gap: 0, overflow: 'hidden', backgroundColor: '#FFFFFF' },
  shippingQuotesListCollapsed: { maxHeight: 70 },
  shippingQuotesFade: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 20 },
  shippingQuote: { minHeight: 20, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: Spacing.two, backgroundColor: '#FFFFFF' },
  shippingQuoteName: { flex: 0.9, minWidth: 0 },
  shippingQuoteEstimate: { flex: 1.35, minWidth: 0, fontSize: 11, textAlign: 'left' },
  shippingQuotePrice: { minWidth: 58, textAlign: 'right' },
  shippingMoreButton: { minHeight: 34, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.one },
  shippingMoreText: { fontSize: 12, textDecorationLine: 'underline' },
  accordion: { marginHorizontal: -Spacing.four, borderTopWidth: 1, borderTopColor: '#e5e0d9' },
  accordionHeader: { minHeight: 32, paddingHorizontal: Spacing.four, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  accordionContent: { gap: Spacing.two, paddingHorizontal: Spacing.four, paddingBottom: Spacing.four },
  accordionTitle: { fontSize: 12, lineHeight: 16, fontWeight: '500' },
  accordionText: { color: '#625d57', lineHeight: 16, fontSize: 12 },
  descriptionTextClip: { position: 'relative', overflow: 'hidden' },
  descriptionTextClipCollapsed: { maxHeight: DESCRIPTION_PREVIEW_LINES * DESCRIPTION_LINE_HEIGHT },
  descriptionTextFade: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 20 },
  readMoreButton: { alignSelf: 'flex-start', paddingVertical: Spacing.one },
  readMoreText: { color: '#0a0a0a', fontSize: 13, lineHeight: 13, fontFamily: Fonts.bold, textDecorationLine: 'underline' },
  dropdownChevron: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '90deg' }] },
  dropdownChevronOpen: { transform: [{ rotate: '-90deg' }] },
  floatingBar: { position: 'absolute', left: 10, right: 10, bottom: 20, minHeight: 50, borderRadius: 50, paddingHorizontal: 20, paddingVertical: Spacing.three, flexDirection: 'row', alignItems: 'center', gap: Spacing.three, backgroundColor: '#fff', shadowColor: '#0a0a0a', shadowOpacity: 0.18, shadowRadius: 8, shadowOffset: { width: 0, height: -2 }, elevation: 8 },
  floatingInfo: { flex: 1, gap: 2 },
  floatingName: { fontSize: 12 },
  floatingButton: { minWidth: 122, minHeight: 46, paddingHorizontal: Spacing.three, borderRadius: 8, flexDirection: 'row', gap: Spacing.two, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0a0a0a' },
  floatingButtonText: { color: '#FFFFFF' },
  lookSection: { gap: Spacing.three, paddingTop: Spacing.four, borderTopWidth: 1, borderTopColor: '#e5e0d9' },
  lookTitle: { fontSize: 25, lineHeight: 31, fontFamily: Fonts.semibold },
  lookSubtitle: { fontSize: 16 },
  lookRow: { flexDirection: 'row', gap: Spacing.three, alignItems: 'flex-start' },
  lookRowOpen: { zIndex: 20 },
  lookImageWrap: { width: 150, height: 208, position: 'relative', overflow: 'hidden', borderRadius: 18, backgroundColor: '#e8e8ea' },
  lookImage: { width: '100%', height: '100%' },
  lookTag: { position: 'absolute', left: 5, right: 5, bottom: 6, minHeight: 25, paddingHorizontal: 8, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255, 255, 255, 0.86)' },
  lookTagInteractive: { flexDirection: 'row', gap: 4 },
  lookTagDisabled: { opacity: 0.7 },
  lookTagText: { fontSize: 12 },
  lookInfo: { flex: 1, gap: Spacing.two },
  lookName: { fontSize: 15, lineHeight: 20 },
  lookPrice: { fontSize: 20, lineHeight: 24 },
  lookSelect: { minHeight: 54, paddingHorizontal: Spacing.three, borderRadius: 6, borderWidth: 1, borderColor: '#0a0a0a', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  lookSelectedValue: { fontSize: 12, lineHeight: 16 },
  lookSelectError: { borderColor: '#ed6560' },
  lookKitSelectors: { gap: Spacing.two },
  lookSelectorWrap: { position: 'relative', zIndex: 10 },
  lookSelectorOpen: { zIndex: 40, elevation: 12 },
  lookOptions: { position: 'absolute', left: 0, right: 0, top: 56, paddingVertical: Spacing.one, borderWidth: 1, borderColor: '#d2ccc4', borderRadius: 6, backgroundColor: '#FFFFFF', zIndex: 30, shadowColor: '#0a0a0a', shadowOpacity: 0.14, shadowRadius: 6, shadowOffset: { width: 0, height: 3 }, elevation: 6 },
  lookOption: { minHeight: 34, paddingHorizontal: Spacing.three, paddingVertical: Spacing.one, justifyContent: 'center' },
  lookOptionText: { fontSize: 12, lineHeight: 16 },
  lookUnavailable: { opacity: 0.45 },
  lookUnavailableText: { textDecorationLine: 'line-through' },
  lookSelectionError: { color: '#ed6560', fontSize: 13, lineHeight: 16 },
  lookAddButton: { minHeight: 42, borderRadius: 8, borderWidth: 1, borderColor: '#0a0a0a', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  lookSummary: { gap: Spacing.three, padding: Spacing.four, borderRadius: 20, alignItems: 'center', backgroundColor: '#f0efed' },
  lookTotal: { fontSize: 24, lineHeight: 30 },
  lookBuyButton: { minWidth: 166, minHeight: 44, paddingHorizontal: Spacing.four, borderRadius: 8, borderWidth: 1, borderColor: '#0a0a0a', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  colorModal: { flex: 1, backgroundColor: '#FFFFFF' },
  colorModalSafeArea: { flex: 1 },
  colorModalHeader: { minHeight: 64, paddingHorizontal: Spacing.four, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#e8e3dc' },
  colorModalClose: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  colorModalCloseText: { fontSize: 24, lineHeight: 28, color: '#0a0a0a', fontWeight: '400' },
  colorModalList: { padding: Spacing.three, paddingBottom: Spacing.five },
  colorModalRow: { gap: Spacing.two },
  colorModalItem: { width: '31.5%', minWidth: 0, marginBottom: Spacing.three, padding: 3, borderRadius: 8, borderWidth: 1, borderColor: 'transparent', backgroundColor: '#FFFFFF' },
  selectedColorModalItem: { borderColor: '#0a0a0a' },
  colorModalImage: { width: '100%', aspectRatio: 0.72, borderRadius: 8, backgroundColor: '#e8e8ea' },
  colorModalName: { minHeight: 34, paddingTop: Spacing.one, fontSize: 11, lineHeight: 15 },
  similarSection: { gap: Spacing.three, marginTop: Spacing.three },
	similarProducts: { fontSize: 16 },
});
