import { Dimensions, StyleSheet } from 'react-native';
import { Fonts, Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  section: { borderRadius: 16, backgroundColor: 'transparent' },
  productShelfSection: { gap: 8, padding: 0, marginHorizontal: 0 },
  homeProductShelfSection: { gap: 8, paddingHorizontal: 0 },
  richTextSection: { gap: 8, padding: 16 },
  streamShopSection: { gap: 8, padding: 16 },
  scheduleSection: { gap: 8, padding: 16 },
  couponsSection: { gap: 8, padding: 16 },
  blogSection: { gap: 8, padding: 16 },
  cmsFallbackSection: { gap: 8, padding: 16 },
  bannerSection: { gap: 6, paddingHorizontal: 10, paddingTop: 0, paddingBottom: 0, borderRadius: 0, marginHorizontal: 0, backgroundColor: 'transparent' },
  homeBannerSection: { marginHorizontal: 0, backgroundColor: '#fff' },
  bannerSectionTitle: { fontSize: 20, lineHeight: 20, color: '#0a0a0a', paddingHorizontal: 0, fontWeight: '600' },
  homeGridBannerSection: { marginHorizontal: 0, paddingHorizontal: 0, backgroundColor: '#fff' },
  homeRoundedBannerSection: { marginHorizontal: 0, paddingHorizontal: 0, backgroundColor: '#fff' },
  homeHorizontalBannerSection: { marginHorizontal: 0, paddingHorizontal: 0, backgroundColor: '#fff' },
  homeSingleBannerSection: { marginHorizontal: 0, paddingHorizontal: 0, backgroundColor: '#fff' },
  homeSliderBannerSection: { marginHorizontal: 0, paddingHorizontal: 0, backgroundColor: '#fff' },
  homeGridBanner: { width: '100%', marginHorizontal: 0, paddingHorizontal: 10 },
  homeGridBannerTitle: { color: '#0a0a0a' },
  homeRoundedBannerTitle: { color: '#0a0a0a', marginHorizontal: 10 },
  homeHorizontalBannerTitle: { color: '#0a0a0a' },
  homeSingleBannerTitle: { color: '#0a0a0a' },
  homeSliderBannerTitle: { color: '#0a0a0a' },
  homeGridBannerOverlayTitle: { color: '#FFFFFF' },
  homeRoundedBannerOverlayTitle: { color: '#FFFFFF' },
  homeHorizontalBannerOverlayTitle: { color: '#FFFFFF' },
  homeSingleBannerOverlayTitle: { color: '#FFFFFF' },
  homeSliderBannerOverlayTitle: { color: '#FFFFFF' },
  homeGridBannerOverlaySubtitle: { color: '#FFFFFF' },
  homeRoundedBannerOverlaySubtitle: { color: '#FFFFFF' },
  homeHorizontalBannerOverlaySubtitle: { color: '#FFFFFF' },
  homeSingleBannerOverlaySubtitle: { color: '#FFFFFF' },
  homeSliderBannerOverlaySubtitle: { color: '#FFFFFF' },
  categoryMenuSection: {
    gap: 12,
    padding: 0,
		marginHorizontal: 0,
		marginVertical: 0,
    borderRadius: 8,
    borderWidth: 0,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    backgroundColor: 'transparent',
  },
  // O hero escapa do padding horizontal usado pelos demais blocos da home.
  heroSection: { width: Dimensions.get('window').width, height: Dimensions.get('window').height, backgroundColor: '#ffffff' },
  heroViewport: { position: 'relative', width: '100%', height: Dimensions.get('window').height },
  bannerSliderViewport: { position: 'relative', width: '100%' },
  heroCarousel: { flex: 1 },
  bannerCarousel: { width: '100%' },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16 },
  seeAll: { textDecorationLine: 'underline', fontSize: 13 },
  tabList: { gap: 8 },
  homeTabList: { paddingHorizontal: 10 },
  tab: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 50, borderWidth: 1, borderColor: '#0a0a0a' },
  selectedTab: { backgroundColor: '#0a0a0a' },
  selectedTabText: { color: '#FFFFFF' },
  homeShelfTitle: { fontSize: 20, lineHeight: 20 },
  homeTabViewport: { marginHorizontal: 0, paddingHorizontal: 0 },
  homeTab: { borderRadius: 50 },
  homeTabText: { fontSize: 14, lineHeight: 16 },
  plpSection: { gap: Spacing.three, backgroundColor: '#ffffff' },
  plpHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.two },
  plpHeading: { flex: 1 },
  plpTitle: { fontSize: 18 },
  plpCount: { fontSize: 12 },
  filterButton: { minHeight: 42, paddingHorizontal: Spacing.three, borderRadius: 22, borderWidth: 1, borderColor: '#6d6862', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.two, backgroundColor: '#FFFFFF' },
  filterButtonText: { fontSize: 12 },
  loadMoreButton: { minHeight: 48, marginTop: Spacing.two, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0a0a0a' },
  loadMoreText: { color: '#FFFFFF', fontWeight: '700' },
  pressed: { opacity: 0.7 },
  sectionTitleCateg: { marginHorizontal: 10, fontSize: 20, lineHeight: 26, color: '#0a0a0a', fontWeight: '700' },
  categorySwipePanel: { overflow: 'hidden', marginHorizontal: 0, paddingLeft: 25, paddingRight: 20, borderRadius: 8, borderWidth: 0, borderColor: 'rgba(255, 255, 255, 0.9)', backgroundColor: 'transparent' },
  categorySwipeRow: { minHeight: 60, paddingHorizontal: 0, paddingVertical: 18, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 0, borderBottomColor: 'rgba(255, 255, 255, 0.82)', backgroundColor: 'transparent' },
  categorySwipeRowTitle: { flex: 1, fontSize: 15, lineHeight: 22, color: '#0a0a0a', fontWeight: '500', textTransform: 'none' },
  categoryModal: { flex: 1, padding: 16, backgroundColor: '#f0f1f5' },
  categoryModalHeader: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.9)' },
  categoryModalBack: { width: 32, height: 36, alignItems: 'center', justifyContent: 'center' },
  categoryModalTitle: { flex: 1, fontSize: 20, lineHeight: 26, color: '#0a0a0a', fontWeight: '700', textAlign: 'center' },
  categoryModalList: { gap: 10, paddingVertical: 16 },
  categoryModalItem: { minHeight: 52, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.82)' },
  categoryModalItemText: { flex: 1, fontSize: 16, lineHeight: 22, color: '#0a0a0a' },
  categoryList: { gap: 0, overflow: 'hidden', borderRadius: 16, borderWidth: 0, borderColor: 'rgba(255, 255, 255, 0.9)', backgroundColor: '#ffffff' },
  categoryGroupsList: { gap: 12, overflow: 'visible', backgroundColor: 'transparent' },
  categoryRow: { minHeight: 64, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.82)' },
  categoryRowTitle: { fontSize: 18, lineHeight: 26, color: '#0a0a0a', fontWeight: '500' },
  categoryGroup: { gap: 14, marginHorizontal: 14, paddingHorizontal: 14, paddingVertical: 18, borderRadius: 16, borderWidth: 0, borderColor: 'rgba(255, 255, 255, 0.9)', backgroundColor: '#ffffff', boxShadow: '0px 0px 10px 1px rgba(0, 0, 0, 0.1)' },
  categoryGroupHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  categoryGroupBack: { width: 28, height: 32, alignItems: 'center', justifyContent: 'center' },
  categoryGroupTitle: { flex: 1, fontSize: 18, lineHeight: 20, color: '#0a0a0a' },
  seeAllButton: { minHeight: 30, paddingHorizontal: 16, borderRadius: 18, borderWidth: 1, borderColor: '#0a0a0a', alignItems: 'center', justifyContent: 'center' },
  seeAllButtonText: { fontSize: 12, lineHeight: 16, color: '#0a0a0a' },
  subcategoryBlock: { borderTopWidth: 1, borderTopColor: '#d4d4d4' },
  subcategoryHeader: { minHeight: 52, paddingHorizontal: 4, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  subcategoryHeading: { fontSize: 16, lineHeight: 22, color: '#0a0a0a', fontWeight: '700' },
  subcategoryChevron: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
  subcategoryChevronExpanded: { transform: [{ rotate: '90deg' }] },
  subcategoryList: { gap: 10 },
  subcategoryRow: { minHeight: 46, paddingHorizontal: 12, justifyContent: 'center', borderLeftWidth: 2, borderLeftColor: '#e2ded8' },
  subcategoryText: { fontSize: 16, lineHeight: 22, color: '#625d57' },
  banner: { overflow: 'hidden', borderRadius: 16 },
  roundedBannerItem: { alignItems: 'center' },
  roundedBannerItemTitle: { marginTop: 4, color: '#0a0a0a', fontSize: 11, lineHeight: 16, fontWeight: '700', textAlign: 'center' },
  bannerTarget: { width: '100%' },
  bannerImage: { width: '100%', backgroundColor: '#e5e7eb' },
  bannerListRow: { flexDirection: 'row', gap: 12 },
  homeHorizontalBannerListRow: { paddingLeft: 10, paddingRight: 10 },
  homeRoundedBannerListRow: { paddingLeft: 10, paddingRight: 10 },
  bannerGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10 },
  fitOnScreenRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  heroBanner: { width: Dimensions.get('window').width, height: Dimensions.get('window').height, minHeight: Dimensions.get('window').height, borderRadius: 0 },
  heroImage: { width: '100%', height: Dimensions.get('window').height },
  heroDots: { position: 'absolute', left: 0, right: 0, bottom: 20, flexDirection: 'row', justifyContent: 'center', gap: 6 },
  homeHeroDots: { bottom: 80 },
  overlay: {
    position: 'absolute',
    left: 16,
    bottom: 16,
  },
  overlayTitle: { color: '#FFFFFF', fontSize: 20, fontWeight: '700' },
  overlaySubtitle: { color: '#FFFFFF', fontSize: 14, marginTop: 4 },
  bannerButtonPosition: { position: 'absolute' },
  bannerButton: { position: 'relative', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderRadius: 24 },
  bannerButtonBlur: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  bannerButtonColor: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  bannerButtonText: { fontFamily: Fonts.bold, fontWeight: '700', textAlign: 'center' },
  tileStack: { gap: 12 },
  contentRow: { flexDirection: 'row', gap: 12 },
  contentCard: { width: 190, gap: 8, padding: 10, borderRadius: 14, backgroundColor: '#FFFFFF' },
  contentCardImage: { width: 170, height: 130, borderRadius: 8 },
  scheduleCard: { flex: 1, minWidth: 130, gap: 6, padding: 12, borderRadius: 14, backgroundColor: '#FFFFFF' },
  couponCard: { gap: 6, padding: 14, borderRadius: 14, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#e0ddd7' },
  couponCode: { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, backgroundColor: '#0a0a0a', color: '#FFFFFF', fontWeight: '700' },
});
